name: '🏷️ Auto Label'

on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: read

jobs:
  auto-label:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: release-drafter/release-drafter/autolabeler@v7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
